# Generated by Django 3.1.2 on 2020-10-27 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20201022_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(help_text='책의 언어를 입력하세요(e.g. English, French, Japanese etc.', max_length=200),
        ),
    ]
